- id: '1736283402815'
  alias: Akvarie Dagslys Tænd
  description: ''
  triggers:
  - trigger: time
    at: '13:00:00'
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      color_temp_kelvin: 6500
      brightness_pct: 50
      transition: 900
    target:
      entity_id: light.akvariebelysning_light
  mode: single
- id: '1736286893021'
  alias: Akvarie Solnedgang
  description: ''
  triggers:
  - trigger: event
    event_type: NautiskTusmoerke
  conditions: []
  actions:
  - action: light.turn_on
    data:
      rgb_color:
      - 223
      - 223
      - 96
      brightness_pct: 35
      transition: 900
    target:
      entity_id: light.akvariebelysning_light
  - type: turn_on
    device_id: 7a2837e395f3bec0db059cc6ec99611f
    entity_id: 07253dc0a3c1062a80f790a7d324bee2
    domain: switch
  mode: single
- id: '1736373519360'
  alias: Akvarie Hydroponisk Lys Sluk
  description: ''
  triggers:
  - trigger: event
    event_type: Sun_Next_Dawn
  - trigger: event
    event_type: Putte_Sove_Nu
  conditions: []
  actions:
  - type: turn_off
    device_id: 7a2837e395f3bec0db059cc6ec99611f
    entity_id: 07253dc0a3c1062a80f790a7d324bee2
    domain: switch
  mode: single
- id: '1736629191491'
  description: Bryggers Lampet Solnedgang
  triggers:
  - trigger: event
    event_type: NautiskTusmoerke
  conditions: []
  actions:
  - action: light.turn_on
    data:
      color_temp_kelvin: 2300
      brightness: 64
    target:
      entity_id: light.bryggers_lampet_light
  mode: single
- id: '1736630015715'
  alias: Bryggers Lampet Sluk
  description: ''
  triggers:
  - trigger: event
    event_type: Putte_Sove_Nu
  - trigger: event
    event_type: Sun_Next_Dawn
  conditions: []
  actions:
  - action: light.turn_on
    data:
      color_temp_kelvin: 2300
      brightness: 0
      transition: 900
    target:
      entity_id: light.bryggers_lampet_light
  - delay: 00:15:00
  - action: light.turn_off
    target:
      entity_id: light.bryggers_lampet_light
    data: {}
  mode: single
- id: '1736706559727'
  alias: Udløs hændelse ved Nautisk Tusmørke
  triggers:
  - entity_id: sun.sun
    attribute: elevation
    below: -6
    trigger: numeric_state
  actions:
  - event: NautiskTusmoerke
    event_data:
      besked: Nautisk tusmørke starter nu
  mode: single
- id: '1736924637953'
  alias: Udløs hændelse v Sun_Next_Dawn
  description: ''
  triggers:
  - at: sensor.sun_next_dawn
    trigger: time
  conditions: []
  actions:
  - event: Sun_Next_Dawn
    event_data:
      besked: Nautisk tusmørke (morgen) slutter nu
  mode: single
- id: '1737050042333'
  alias: Udløs Event Putte_Sove_Nu
  description: ''
  triggers:
  - trigger: time
    at: 00:15:00
  conditions: []
  actions:
  - event: Putte_Sove_Nu
    event_data:
      besked: Nu er det tid til at putte sove
  mode: single
- id: '1737248891058'
  alias: Akvarie Lys Sluk
  description: ''
  triggers:
  - trigger: event
    event_type: Sun_Next_Dawn
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data:
      transition: 900
    target:
      device_id: 407c2e1749042a9f669d3b5ab2bd207b
  mode: single
- id: '1745259648525'
  alias: Natpisning
  description: Natpisser spottet i sovekammer
  triggers:
  - type: motion
    device_id: df16711274db6405e3996dcc8215f9a2
    entity_id: 24e1b72de38d5af81cb956b5791b8e65
    domain: binary_sensor
    trigger: device
  conditions:
  - type: is_illuminance
    condition: device
    device_id: 0235c28c0074ca4912fc6464e09c1318
    entity_id: 8401c5d8dbf7628a845860c42b315185
    domain: sensor
    below: 10
  - condition: device
    type: is_off
    device_id: 35a2cb2078c23debc3ad197e4698aac8
    entity_id: 866ce146e5f94fff6b8d6b4388a735ea
    domain: light
  - type: is_power
    condition: device
    device_id: 62a735460bdd5adf829de3f7ebe1146e
    entity_id: ac1ee4dd43adf51f8344b94aee72d8a6
    domain: sensor
    below: 1
  actions:
  - action: light.turn_on
    data:
      color_temp_kelvin: 2300
      brightness: 32
    target:
      entity_id: light.bryggers_lampet_light
  - type: turn_on
    device_id: 521b537056b8b1de2c857e099ada9bc3
    entity_id: 65c39a37a394572434cd366c0c14cb4c
    domain: switch
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      device_id: aeb7b14677fad1c783bfa73cb3003642
  - delay:
      hours: 0
      minutes: 8
      seconds: 0
      milliseconds: 0
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 35a2cb2078c23debc3ad197e4698aac8
  - type: turn_off
    device_id: 521b537056b8b1de2c857e099ada9bc3
    entity_id: 65c39a37a394572434cd366c0c14cb4c
    domain: switch
  - type: turn_off
    device_id: aeb7b14677fad1c783bfa73cb3003642
    entity_id: 2249075fef3f1d660569e70c39c040a8
    domain: switch
  mode: single
- id: '1753641710935'
  alias: 'Morgenkaffe '
  description: ''
  triggers:
  - trigger: time
    at: 05:55:00
  conditions:
  - condition: time
    weekday:
    - fri
    - thu
    - wed
    - tue
    - mon
  actions:
  - type: turn_on
    device_id: 480950dc9db54b106ce21b15a47fafc5
    entity_id: 82f981d1018befb10e2949ab0c6cfbe8
    domain: switch
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 480950dc9db54b106ce21b15a47fafc5
    entity_id: 82f981d1018befb10e2949ab0c6cfbe8
    domain: switch
  mode: single
- id: '1755113483222'
  alias: Akvarie Natlys
  description: ''
  triggers:
  - trigger: event
    event_type: Putte_Sove_Nu
  conditions: []
  actions:
  - action: light.turn_on
    data:
      brightness_pct: 1
      transition: 900
      color_temp_kelvin: 2101
    target:
      entity_id: light.akvariebelysning_light
  mode: single
- id: '1756268663999'
  alias: Skrivebord Ambient
  description: ''
  triggers:
  - device_id: a4e44b65dac08c49617a5651adcd5513
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: switch.toggle
    metadata: {}
    data: {}
    target:
      entity_id: switch.lampe_skrivebord_ambient_socket_1
  mode: single
- id: '1756272538097'
  alias: Stue Lys
  description: ''
  triggers:
  - device_id: a4e44b65dac08c49617a5651adcd5513
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions: []
  mode: single
